work_dir: ./work_dir/recognition/ntu-xsub/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: /nfs/users/wangkun/datasets/NTU/NTU-RGB-D/NTU60_frame64/xsub/train_position.npy
  label_path: /nfs/users/wangkun/datasets/NTU/NTU-RGB-D/NTU60_frame64/xsub/train_label.npy
test_feeder_args:
  data_path: /nfs/users/wangkun/datasets/NTU/NTU-RGB-D/NTU60_frame64/xsub/val_position.npy
  label_path: /nfs/users/wangkun/datasets/NTU/NTU-RGB-D/NTU60_frame64/xsub/val_label.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 64 
test_batch_size: 64
num_epoch: 80



